### ISSUE TITLE
generated main does not compile on OSX

### ISSUE THREAD

**Issue by smits** [orocos-toolchain/orogen#47]
I got the following compile error for an orogen generated project:

big_mockup/.orogen/main-orogen_default_big_mockup__Workaround.cpp:286:20: error: 
      no member named 'sa_restorer' in 'sigaction'
    sigint_handler.sa_restorer  = 0;
    ~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.

The Linux manpage (http://man7.org/linux/man-pages/man2/sigaction.2.html) mentions the following:

The sa_restorer field is not intended for application use.  (POSIX
       does not specify a sa_restorer field.)  Some further details of
       purpose of this field can be found in sigreturn(2).

It's probable safe to remove this line?

**Comment by goldhoorn** [comment]
Please try your suggested fix by removing the line from:

https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/templates/main.cpp#L383

Test it on your installation and create a PR, for me it looks save to remove it. (what i wonder about we currently porting rock to osx and it works on osx 10.10)

**Comment by smits** [comment]
Removed the line and it compiles. I'm not really using the main at all (only the typekits), so I have no idea if it would break anything. I'd rather have someone else do a test on a full featured project to make sure it does not break the related behavior.

**Comment by goldhoorn** [comment]
My manpage mentions this behaviour not, to keep the clean initialization i would prefer a 
```
#ifndef __APPLE__
sigint_handler.sa_restorer = 0;
#endif
```

instead removing it and create theoretical uninitialized structures.

**Comment by doudou** [comment]
I actually don't know what's the policy to initialize these structures. In this particular case, doing

```
memset(&sigint_handler, 0, sizeof(sigint_handler))
```

would do the trick without having to care about platform weirdness

**Comment by goldhoorn** [comment]
@smits: please check the pr #49 on macos, for Linux it's already tested.

**Comment by smits** [comment]
Works for me, but I don't like the unrelated include of string.h, makes it harder to cherry-pick.

**Comment by smits** [comment]
I agree with including string.h for memset as you explained.
